config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :pantries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'pantries/find_by_name_or_category' => 'pantries#find_by_name_or_category'
  root 'pantries#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

end

app/models/pantry.rb
class Pantry < ApplicationRecord
  validates_presence_of :item_name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category_name)
    end
end

app/controllers/pantries_controller.rb
class PantriesController < ApplicationController
  before_action :set_pantry, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with name: "cs83r", password: "rubyonrails", except: [:index, :show]

  def find_by_name_or_category
    @pantries = Pantry.where("item_name=? or category=?", params[:search_string], params[:search_string])
  end


  # GET /pantries
  # GET /pantries.json
  def index
     @pantries = Pantry.order(:category)
  end

  # GET /pantries/1
  # GET /pantries/1.json
  def show
  end

  # GET /pantries/new
  def new
    @pantry = Pantry.new

  end

  # GET /pantries/1/edit
  def edit
  end

  # POST /pantries
  # POST /pantries.json
  def create
    @pantry = Pantry.new(pantry_params)

    respond_to do |format|
      if @pantry.save
        format.html { redirect_to @pantry, notice: 'Pantry was successfully created.' }
        format.json { render :show, status: :created, location: @pantry }
      else
        format.html { render :new }
        format.json { render json: @pantry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pantries/1
  # PATCH/PUT /pantries/1.json
  def update
    respond_to do |format|
      if @pantry.update(pantry_params)
        format.html { redirect_to @pantry, notice: 'Pantry was successfully updated.' }
        format.json { render :show, status: :ok, location: @pantry }
      else
        format.html { render :edit }
        format.json { render json: @pantry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pantries/1
  # DELETE /pantries/1.json
  def destroy
    @pantry.destroy
    respond_to do |format|
      format.html { redirect_to pantries_url, notice: 'Pantry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pantry
      @pantry = Pantry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pantry_params
      params.require(:pantry).permit(:item_name, :category, :qty, :date_of_purchase, :order_more)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pantries_helper.rb
module PantriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="media">
      <div class="media media-body">
          <div class="field">
            <%= form.label :category_name %>
            <%= form.text_field :category_name %>
          </div>

          <div class="actions">
            <%= form.submit %>
          </div>
      </div>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h1>Categories</h1>
<div class="media">
  <div class="media-body">
    <table class="table table-hover">
        <thead>
          <tr>
            <th>Category name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.category_name %></td>
              <td><%= link_to 'Show', category, class: 'btn btn-mini' %></td>
              <td><%= link_to 'Delete', category, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>


<br>

<%= link_to 'New Category', new_category_path, class: 'btn btn-mini' %> |
<%= link_to 'Back to Pantry', pantries_path, class: 'btn btn-mini' %>
</div>

app/views/categories/new.html.erb
<div class="container">
<h1>New Category</h1>

  <%= render 'form', category: @category %>
  <%= link_to 'Back to Pantry', pantries_path, class: 'btn btn-mini' %> |
  <%= link_to 'Edit Category list', categories_path, class: 'btn btn-mini' %>
</div>

app/views/categories/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Category name:</strong>
  <%= @category.category_name %>
</p>


<%= link_to 'Back', categories_path, class: 'btn btn-mini' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KitchenCabinet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pantries.erb
<!DOCTYPE html>
<html>
<head>
  <title>KitchenCabinet</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<br>
<div class="container">
  <div class="nav nav-toggle">

  <form class="form-inline md-form form-sm active-cyan-2 mt-2" <%= form_tag "/pantries/find_by_name_or_category" do %>
    <input class="form-control form-control-sm mr-3 w-75" type="text" placeholder="Search" aria-label="Search" <%= text_field_tag :search_string %>
    <%= submit_tag "search", class: 'btn btn-medium btn-info' %>
  </form>
    <% end %>

    <%= link_to 'Add Item to Pantry', new_pantry_path, class: 'btn btn-mini' %> |
    <%= link_to 'Create Category', new_category_path, class: 'btn btn-mini' %> |
    <%= link_to 'Back', pantries_path, class: 'btn btn-mini' %>
  </div>

</div>
  <%= yield %>

</body>
</html>

app/views/pantries/_form.html.erb
<%= form_with(model: pantry, local: true) do |form| %>
  <% if pantry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pantry.errors.count, "error") %> prohibited this pantry from being saved:</h2>

      <ul>
      <% pantry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="media">
      <div class="media media-body">

  <div class="field">
    <%= form.label :item_name %>
    <%= form.text_field :item_name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select :category, Category.all.collect{|ca| [ca.category_name, ca.category_name,]},{include_blank: true } %>
  </div>

  <div class="field">
    <%= form.label :qty %>
    <%= form.select(:qty, options_for_select([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10]])) %>
  </div>

  <div class="field">
    <%= form.label :date_of_purchase %>
    <%= form.date_select :date_of_purchase %>
  </div>

  <div class="field">
    <%= form.label :order_more %>
    <%= form.select(:order_more, options_for_select([['YES', 'YES'], ['NO', 'NO']]), {include_blank: true }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

      </div>
    </div>
  </div>


<% end %>

app/views/pantries/edit.html.erb
<div class="container">
<h1>Editing Pantry</h1>

<%= render 'form', pantry: @pantry %>

</div>

app/views/pantries/find_by_name_or_category.erb
<div class="container">
<h1> Searched </h1>


<div class="nav-section">
<%= link_to 'Back', pantries_path, class: 'btn btn-mini' %>
<%= link_to 'New Pantry', new_pantry_path, class: 'btn btn-mini' %>
</div>
<br>
<br>
<div class="media">
  <div class="media-body">
    <table class="table table-hover">
        <thead>
        <tr>
          <th>Item name</th>
          <th>Category</th>
          <th>Qty</th>
          <th>Date of purchase</th>
          <th>Order More</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        </thead>

        </tbody>
        <% @pantries.each do |food| %>
          <tr>
            <td><%= food.item_name %></td>
            <td><%= food.category %></td>
            <td><%= food.qty %></td>
            <td><%= food.date_of_purchase %></td>
            <td><%= food.order_more %></td>
            <td><%= link_to 'Edit', edit_pantry_path(food), class: 'btn btn-mini' %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
  </div>
</div>


<br>
</div>

app/views/pantries/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h1>What's in my Pantry</h1>

<div class="media">
  <div class="media-body">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Item name</th>
            <th>Category</th>
            <th>Qty</th>
            <th>Date of purchase</th>
            <th>Order more</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @pantries.each do |pantry| %>
            <tr>
              <td><%= pantry.item_name %> </td>
              <td><%= pantry.category %> </td>
              <td><%= pantry.qty %> </td>
              <td><%= pantry.date_of_purchase %> </td>
              <td><%= pantry.order_more %> </td>
              <td><%= link_to 'Show', pantry, class: 'btn btn-mini'%></td>
              <td><%= link_to 'Edit', edit_pantry_path(pantry), class: 'btn btn-mini btn-success' %></td>
              <td><%= link_to 'Delete', pantry, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>
<br>
</div>

app/views/pantries/new.html.erb
<div class="container">


<h1>Add New Item in Pantry</h1>


<%= render 'form', pantry: @pantry %>

</div>

app/views/pantries/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Item name:</strong>
  <%= @pantry.item_name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @pantry.category %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @pantry.qty %>
</p>

<p>
  <strong>Date of purchase:</strong>
  <%= @pantry.date_of_purchase %>
</p>

<p>
  <strong>Order more:</strong>
  <%= @pantry.order_more %>
</p>

</div>